### ISSUE TITLE
Effect of xform attribute on tests

### ISSUE THREAD

**Issue by jonclayden** [martin3141/spant#11]
Hi Martin. To [ensure that xform matrices preserve origins when reoriented](https://github.com/jonclayden/RNifti/issues/23), the development version of `RNifti` adds an `imagedim` attribute to those matrices. Unfortunately this makes this `spant` test fail, because attributes don't match:

https://github.com/martin3141/spant/blob/3d8925f072628ddb5e3c0c9cbd522d57062fe062/tests/testthat/test_nifti.R#L36

One workaround is to add `check.attributes = FALSE` to the test, but a better one might be to strip all "nonstandard" attributes, not just `code`, when the file is read in:

https://github.com/martin3141/spant/blob/3d8925f072628ddb5e3c0c9cbd522d57062fe062/R/mrs_read_nifti.R#L55-L62

For example,

```r
attributes(affine) <- list(dim=dim(affine))
```

would retain only the `dim` attribute, and drop all others.

I need to submit a CRAN update for `RNifti` imminently due to a prompt from them about something else, but I don't want to break your test without notice. Would you be OK to resolve this breakage and provide an updated `spant` for CRAN, or shall I revert this change for now to give you more time?

All the best.

**Comment by jonclayden** [comment]
I'm happy to put the change above into a pull request, if that would be helpful.

**Comment by martin3141** [comment]
Hi Jon. No problem, I've made the update and the test passes with the development version of RNifti. Do you want to double check  at your end before I submit to CRAN?

**Comment by jonclayden** [comment]
Looks good over here! Many thanks for being so quick and accommodating. I'll get my submission done too then.

**Comment by martin3141** [comment]
The next version of spant is on its way to CRAN, so you should be all clear to submit now. Best wishes.
