### ISSUE TITLE
Documentation - Tarquin and LCModel path

### ISSUE THREAD

**Issue by slieped** [martin3141/spant#5]
From the documentation of the function fit_mrs(), it reads that to modify both Tarquin and LCModel path, to use the functions set_tqn_path() and set_lcm_path().

This functions do not exist. I guess it refers to set_tqn_cmd(), right?
Just notify to update the documnetation

thanks for the package! I used to work with Tarquin, but really enjoying spant :)

**Comment by martin3141** [comment]
Thanks for spotting the error, this will be fixed in the next release (1.2.0).

You might be also be interested in trying the ABfit method : https://www.biorxiv.org/content/10.1101/2020.02.17.949495v1.full - which will generally have better support compared to LCModel and TARQUIN.
