### ISSUE TITLE
Load data with Tarquin

### ISSUE THREAD

**Issue by slieped** [martin3141/spant#6]
I am going through the tutorial to run a very simple fitting of my MRS 1H brain data.
My input format is dicom, so I am trying to use the function read_mrs_tqn().
I realized that, when trying to perform further preprocessing steps (like HSVD filtering), the package fails (dont find appropriate attributes). This is because the open file, do have two mrs_data objects (metab and ref). 

Maybe this should be changed to as default select $metab, or creating two different/independent objects? Or at least, specify this in the preprocessing functions or the read_mrs_tqn() documentation.

Thanks Martin!

**Comment by martin3141** [comment]
Good point. I think a check on the function input, combined with a more helpful message about what went wrong is the way to go here. R only allows the return of one object from a function, so if you want two objects to be returned they need to be in a list.

**Comment by martin3141** [comment]
Will be fixed in the next release.
