### ISSUE TITLE
Write into table PVC/non-PVC

### ISSUE THREAD

**Issue by slieped** [martin3141/spant#7]
Hi Martin, 

I have been doing some tests related to exporting the results_fit objects.
From the help page of the function fit_tab2csv(), it is not clear that the user has to specify the table to export (e.g fit_res$data or fit_res$res_tab_molal_pvc). In addition, from the code, the input argument pvc is not used at all (probably, because the user has to input specifically the table and not the fit_res - and then parse if iths the pvc table or the raw table).

just FYI,

**Comment by martin3141** [comment]
Agreed. The option has been removed and there should only be two types of results table in the next version - scaled and unscaled.
